name: Bug Report
description: Report a Bug for MarkersExtractor
title: "[Bug]: "
labels: "bug"
body:
- type: input
  attributes:
    label: Airlife Version?
    description: Which version of Airlift are you using? If unsure, run `markers-extractor-cli --version`
  validations:
    required: true
- type: dropdown
  attributes:
    label: What OS are you using?
    options:
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
- type: input
  attributes:
    label: macOS Version
    description: Which macOS version are you using?
    placeholder: "e.g. macOS Sonoma 14.1.1"
  validations:
    required: true
- type: textarea
  attributes:
    label: Bug Description
    description: A clear description of the bug and how to reproduce it.
  validations:
    required: true
- type: textarea
  attributes:
    label: Log excerpt
    description: If possible, please attach log excerpt
    render: shell
