public enum MarkerCSVHeader: String, CaseIterable {
    case id = "Marker ID"
    case name = "Marker Name"
    case type = "Type"
    case checked = "Checked"
    case status = "Status"
    case notes = "Notes"
    case position = "Marker Position"
    case clipName = "Clip Name"
    case clipDuration = "Clip Duration"
    case role = "Role & Subrole"
    case eventName = "Event Name"
    case projectName = "Project Name"
    case libraryName = "Library Name"
    case iconImage = "Icon Image"
    case imageFileName = "Image Filename"
}
