name: build
permissions:
  contents: read

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      - '**/*.png'      # .png image files anywhere in the repo
      - '**/*.pdf'      # .pdf files anywhere in the repo
      
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      - '**/*.png'      # .png image files anywhere in the repo
      - '**/*.pdf'      # .pdf files anywhere in the repo
      
  workflow_dispatch:
    
  schedule:
    - cron: '30 10 * * *'   # once a day @ 10:30am UTC (3:30am PST)
    
jobs:
  macOS:
    name: macOS
    runs-on: macos-15 # required for Xcode 16.x
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "MarkersExtractor-Package" -destination "generic/platform=macOS,name=Any Mac" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
