# workflow runs on successful completion of the build workflow, or when manually run

name: unit-tests

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
  
  workflow_dispatch:
  
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-15 # required for Xcode 16.x
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Set Package to Swift 6.0
      run: swift package tools-version --set "6.0"
    - name: Unit Tests
      run: xcodebuild test -skipMacroValidation -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "MarkersExtractor-Package" -destination "platform=macOS" | xcbeautify && exit ${PIPESTATUS[0]}
